version: 2
updates:

  - package-ecosystem: "maven"
      directory: "/backend"
      target-branch: "development"
      schedule:
        interval: "weekly"
        day: "sunday"
      labels:
        - "dependencies"

  - package-ecosystem: "npm"
      directory: "/frontend/schedulator3000"
      target-branch: "development"
      schedule:
        interval: "weekly"
        day: "saturday"
      labels:
        - "dependencies"
