name: Clojure Version Bump

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v2

    - name: Bump Version
      id: bump
      uses: BertSa/maven-version-bump-action@master
      with:
        github-token: ${{ secrets.github_token }}
        pom-path: './backend'
        package-json-path: './frontend/schedulator3000'

    - name: Print Version
      run: "echo 'New Version: ${{steps.bump.outputs.version}}'"
