name: 'Bump Version'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name:  'Automated Version Bump'
        id: version-bump
        uses:  'BertSa/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR:  'frontend/schedulator3000'
        with:
          tag-prefix: 'v'
          minor-wording: '#minor'
          major-wording: '#major'
          commit-message: 'Update to : {{version}}'
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
